### ISSUE TITLE
Multi-task training using flow_from_dataframe

### ISSUE THREAD

**Issue by wojsla** [keras-team/keras-preprocessing#197] opened 2019-04-09 08:03 UTC
I am trying to use flow_from_dataframe for multi-task model training. When I use it for a single task multi-class classification model with a dataframe like:
```
       File   Class
0  file1.png  class1
1  file2.png  class2
2  file3.png  class3
3  file4.png  class4
4  file5.png  class5
5  file6.png  class6
6  file7.png  class7
7  file8.png  class8
```

then generator.next() returns tuple where first object is the image and second is an array like:
> array([[0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

for image labeled as class 5.

Now, I want to add a second output to this model that will be a binary classification. The dataframe now looks like:
```
       File MultiClass BinaryClass
0  file1.png     class1         yes
1  file2.png     class2          no
2  file3.png     class3         yes
3  file4.png     class4          no
4  file5.png     class5         yes
5  file6.png     class6          no
6  file7.png     class7         yes
7  file8.png     class8          no
```
I configured generator's class_mode to "multi_output" and y_col to ['MultiClass', 'BinaryClass']. Now when requesting next from it I again receive a tuple with image as first object, but second object looks like this:
> array([['class1', 'yes']], dtype=object))

and when I run fit_generator I receive this error:

> ValueError: Error when checking target: expected MultiClass to have shape (8,) but got array with shape (1,)

How can I configure generator to work correctly in this multi-task/output scenario?

**Comment by rragundez** [comment] 2019-04-09 08:22
Hi @wojsla , `multi_output` outputs as a target whatever is in the columns, it does not convert your classes into one hot encoded vectors, this is because the columns can have different type of conversions e.g. binary, multi_class, regression
Take a looks at this quick example https://gist.github.com/rragundez/8b1b9e190abef8ffb6d93f03f8e0e091
in the multi_task section where I have to use `to_categorical` in order to do the one-hot expansion myself before feeding the generator.

In your case you need to apply `to_categorical` to the `MultiClass` and use `categorical_crossentropy` as loss for that one and then convert the column `BinaryClass` into ones and zeros with `binary_crossentropy` loss. Similar to what I do in the example with `races` and `gender` columns respectively. 
Is this clear? can we close the issue?

**Comment by wojsla** [comment] 2019-04-10 07:16
@rragundez thanks a lot. Should I add a PR with optional arguments to specify conversion type for each column?

**Comment by rragundez** [comment] 2019-04-11 07:03
I think is best if you first submit an API change proposal, to see how you plan to implement it and then we have a discussion. I've thought about it before and for lack of time haven't been able to implement but in my opinion all this logic, of what columns to use and how to convert them, should be triggered with a single parameter, `y_col`. This will mean though that `y_col` should be able to receive a string for a single column, a list for multiple columns and a dictionary for columns name: output mode combination. Then you will have that the output mode parameter should be removed as it will not be necessary. Something like that. 

In any case thanks for reporting this issue, it seems that the documentation needs a bit of work. If you would like to help with improving it, that would be super.

**Closed by rragundez** 2019-04-11 07:03 UTC
Labels: image

**Comment by wojsla** [comment] 2019-04-12 06:11
@rragundez where can I submit this change proposal? happy to help improving it

**Comment by rragundez** [comment] 2019-04-12 22:08
I think this change requires some discussion and it might be good to follow the guide in step 1 for PRs https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md
Start there and then we can try to separate the work in small PRs.
