### ISSUE TITLE
next() does not work correctly with imagedatagenerator

### ISSUE THREAD

**Issue by IIIBlueberry** [keras-team/keras-preprocessing#226] opened 2019-07-24 15:08 UTC
in my directory i have 95,889 of images after a while training my model(batch size of 16) using next() and model.train_on_batch() i getting this error after around 5991 steps and my training stop https://i.imgur.com/y7NVNDC.png
python script gist : https://gist.github.com/IIIBlueberry/55c78d6bb8d656d39040447dff9a4673
- [x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rragundez** [comment] 2019-07-25 00:38
Hi can you please provide a minimal reproducible example? thanks

**Comment by IIIBlueberry** [comment] 2019-07-25 05:22
> 
> 
> Hi can you please provide a minimal reproducible example? thanks

hi here it is,i got the same problem with this code
[Imgur](https://imgur.com/0op5YNg)

```
import keras
from keras.layers import Conv2D
from keras.models import Sequential
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator
steps = 100000
batch_size = 16
#Load Datasets from directory
datagen = ImageDataGenerator(rescale=1.0/255.0, horizontal_flip=True)
datagenerator = datagen.flow_from_directory('dataset', target_size=(64, 64), class_mode=None, batch_size=batch_size)
def build_ae():
    model = Sequential([
        Conv2D(64, (3, 3), padding='same', input_shape=(64, 64, 3), name='encoder'),
        Conv2D(3, (3, 3), padding='same', activation='sigmoid', name='decoder'),
    ])
    return model
# Create AE and DIS
ae = build_ae()
# Compile Dis
ae.compile(loss='mse',
            optimizer=Adam(lr=0.0003),)
imgs_static = next(datagenerator)
ae.summary()
print(imgs_static.shape)
for step in range(steps):
    imgs = next(datagenerator)

    #train ae
    g_loss = ae.train_on_batch(imgs, imgs_static)

    print ("%d [G loss: %f]" % (step, g_loss))
```

**Comment by IIIBlueberry** [comment] 2019-07-29 17:19
Any update on this issues?
\

**Comment by rragundez** [comment] 2019-07-31 00:00
that's not a minimal reproducible example. I cannot reproduce the bug as I do not have that data. Also the bug is in the generator, building a model is not necessary. In general you can follow these guidelines to help us work on this issue better and faster

- Don't use custom data or custom paths.
- Use random arrays or even np.ones, np.zeros.
- The example should run with Keras (and deps) alone.
- Should be Python3 compatible.
- Should not be OS specific.
- The file should reproduce the bug with *high fidelity.

**Comment by rragundez** [comment] 2019-07-31 00:46
Perhaps what you are experiencing is that the last batch will be the remaining number of samples if the number of sample is less than the batch size.  As you can see below I made a minimal example where the number of images is 5 and the batch size is 3, the first batch consist of 3 samples and the second consist of 2, since those are the number of samples remaining.

```
from keras_preprocessing.image import ImageDataGenerator, save_img
import numpy as np
import os

batch_size = 3
n_images = 5

directory = '/tmp/test'
classes = ['dog', 'cat']

for i in range(n_images):
    label = np.random.choice(classes)
    os.makedirs(os.path.join(directory, label), exist_ok=True)
    filename = os.path.join(directory, label, str(i) + '.jpg')
    save_img(filename, np.ones((64, 64, 3)))
    
gen = ImageDataGenerator().flow_from_directory(
    '/tmp/test',
    class_mode=None,
    batch_size=batch_size
)

imgs = next(gen)
print(imgs.shape)
    
imgs = next(gen)
print(imgs.shape)
>>> Found 5 images belonging to 1 classes.
>>> (3, 256, 256, 3)
>>> (2, 256, 256, 3)
```
I will close this issue now.

**Closed by rragundez** 2019-07-31 00:46 UTC
Labels: image

**Comment by IIIBlueberry** [comment] 2019-07-31 02:06
@rragundez Whoops my bad. Based on my i guess that was the error i get, anyway is there solution for this issue?

**Comment by rragundez** [comment] 2019-07-31 18:30
The bug you are facing is due to your implementation not with the package itself.

**Comment by IIIBlueberry** [comment] 2019-07-31 18:39
@rragundez oh is there anyway to loop through the images? i really need to use the next() to predict and train using ttrain_on_batch

**Comment by IIIBlueberry** [comment] 2019-08-01 00:18
@rragundez after doing abit of research i think it was caused by this PR https://github.com/keras-team/keras/pull/11039 which disable infinite loop by default(to fix this problem https://github.com/keras-team/keras-preprocessing/issues/45), also it seems there is no option to re-enable infinite loop for far. And the keras Image Preprocessing docs is also outdated(and manual examples*) as it says 'The data will be looped over (in batches).'(which make me confused). My current solution i guess is downgrade to keras 2.2.2
