### ISSUE TITLE
ImageDataGenerators ``standardize`` modifies input

### ISSUE THREAD

**Issue by alxy** [keras-team/keras-preprocessing#85] opened 2018-10-26 12:29 UTC
I am not sure if this is a bug or intended functionality, but I realized that ``ImageDataGenerator``s ``standardize()`` method is actually modifying the input passed to it. This can be quite annoying in the context of jupyter notebook, when you want to reuse the raw images again. Consider the following example code:

```python
from keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale=2)

images = np.ones((10, 128, 128, 3))
print(images.mean()) # 1.0

images_std = datagen.standardize(images)

print(images.mean(), images_std.mean()) # 2.0 2.0
```

I tracked this down to the fact, that this function uses the shorthand operator for simple arithmetic operations: https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L1124 The following two functions do exactly the same thing, however the first one does not modify the input while the second does:

```python
def multiply1(x):
    x = x * 2

def multiply2(x):
    x *= 2
    
    
images = np.ones((10, 128, 128, 3))
print(images.mean()) # 1.0

multiply1(images)
print(images.mean()) # 1.0

multiply2(images)
print(images.mean()) # 2.0
```

Note that the behavior also differs for different standardization steps, e.g. ``zca_whitening`` does not modify the input while ``rescale`` does.

**Comment by Dref360** [comment] 2018-10-27 13:52
It is as designed, mostly to reuse memory when possible. When using jupyter, I would suggest providing a copy of the input instead.

**Comment by rragundez** [comment] 2019-01-12 19:05
In this case I agree with @alxy. This is a bad practice and should be avoided, as it is an unexpected behavior that faces the user and can have unexpected consequences. Since Keras puts the user first this should be avoided on any function facing the user directly. The behavior of course reduces the memory footprint and can bring benefits, but it should only be used on internal logic not on top-level user facing functions.

That's why for example we do this: https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/dataframe_iterator.py#L106 even though this holds two copies of the dataframe at some point in time, but the user is first so we do it.

I made a PR #138 to address this issue. If there are more places where this happens it should be addressed as well.

**Comment by gglanzani** [comment] 2019-01-15 21:48
Modify in place wouldn't be bad if you wouldn't return a value.

If the user wishes to save memory, passing an extra param (in_place for example) is better suited.

**Comment by rragundez** [comment] 2019-01-16 07:47
@Dref360 should we merge the related PR and close this issue? then we can discuss the introduction of an inplace argument or so. I need a review on the PR though before I can merge.

**Comment by rragundez** [comment] 2019-01-17 07:43
Good point, specially because it is used internally by the `ImageDataGenerator` in this way. I'll update the PR, thanks for the feedback.

**Comment by gabrieldemarmiesse** [comment] 2019-01-20 20:18
I believe this can be closed.

**Closed** 2019-01-20 20:19 UTC
Labels: image
