### ISSUE TITLE
flow_from_dataframe() how to disable sorting?

### ISSUE THREAD

**Issue by aarondt** [keras-team/keras-preprocessing#128] opened 2019-01-01 21:41 UTC
I am using keras's data generator with flow_from_dataframe. for training it works just fine, but when using model.predict_generator on the test set, I discovered that the ordering of the generated results is different than the ordering of the "id" column in my dataframe.

shuffle=False does make the ordering of the generator consistent, but it is a different ordering than the dataframe. I also tried different batch sizes and the corresponding correct steps for the predict_generator function. (for example: batch_Size=1, steps=len(data))

I realize that in the tutorial found here https://medium.com/@vijayabhaskar96/tutorial-on-keras-flow-from-dataframe-1fd4493d237c it mentions a "sort" parameter.

> sort: If you want to sort the x_col column values in ascending order set to True(default) else False.

however this parameter seems to be gone in the latest release?

Currently the only solution that works for me is inferring the ordering obtained with the generator.filenames property.

Is there an alternative solution on how to make sure the labels predicted for my test set are ordered in the same way of my dataframe "id" column?

**Comment by Vijayabhaskar96** [comment] 2019-01-03 11:09
If you have set both `sort=False`(which will be removed soon) and `shuffle=False` the generator.filenames should have the same order as your dataframe, unless drop_duplicates=True and your dataframe has duplicates removing it messes up the order of filenames. You can alaways create a new dataframe with generator.filenames and the predictions, finally merge with your original dataframe though.

**Comment by rragundez** [comment] 2019-01-06 10:36
@aarondt did @Vijayabhaskar96 answered your question? can @Dref360 close this issue then.

**Comment by rragundez** [comment] 2019-01-07 17:37
Can you set `shuffle=False`? That should keep the same order.

**Comment by rragundez** [comment] 2019-01-08 04:45
@aarondt Can you confirm that this above solves your issue so this ticket can be closed?

**Comment by aarondt** [comment] 2019-01-09 16:11
@rragundez @Vijayabhaskar96 thank you guys for your fast response! I am using shuffle=False, however my generator still does not retain the order of my passed dataframe. For reference this is the code I am using:

```
test_datagen=ImageDataGenerator(preprocessing_function=preprocess_input)
test_generator = test_datagen.flow_from_dataframe(dataframe=test_data[["url",target]], directory=bilder_resized_dir, x_col="url", y_col=target, 
                                            has_ext=False, class_mode="categorical", color_mode=color_mode, target_size=(IMG_SIZE,IMG_SIZE), batch_size=div, shuffle=False,classes=class_list)

STEPS = test_generator.n // test_generator.batch_size

preds = model.predict_generator(test_generator,verbose=1,steps=STEPS,workers=15)
```

After running model.predict, I need to reconstruct the correct ordering of the predictions to match them with my original dataframe. I do this by using the filenames of the images as a reference. This is the code I am using:

```
pred_df = pd.DataFrame(list(zip(test_generator.filenames,preds,test_generator.classes)),columns=["filename","preds","true"])
test_data["filename"] = test_data.url.apply(lambda x: x + ".jpg")
img_preds = pd.merge(test_data,pred_df,how="left",on="filename")
img_preds["num_labels_predicted"] = img_preds.preds.apply(lambda x: np.argmax(x))
```

Am I missing something here?

**Comment by rragundez** [comment] 2019-01-09 16:51
@aarondt I don't see where the problem is, how do you know that `preds` is in the wrong order?

**Comment by aarondt** [comment] 2019-01-09 18:11
@rragundez you are right, I should have added a test. Let me explain fruther: I am testing this by comparing the ordering of `test_generator.classes` with the ordering of my "labels" column in my `test_data` dataframe. As such, the situation looks as follows:

`target = "labels"`

```
In [1]: 
test_data[target][:5]

Out[1]:   
0      Berlin
10     Frankfurt
23     Frankfurt
97     Frankfurt
184    Frankfurt
Name: labels, dtype: object
```

now I am using the `class_list `which I passed to the `classes` parameter in my `test_datagen.flow_from_dataframe(..) `declaration:

```
In[2]:
[class_list[x] for x in test_generator.classes][:5]

Out[2]:
['Frankfurt', 'Frankfurt', 'Stuttgart', 'Frankfurt', 'Frankfurt']
```

Which tells me that the ordering of labels seems to be wrong. However, once I sort my dataframe by "url" which are essentially my filenames, everything looks correct:

```
In[3]:
test_data[["url",target]].sort_values(by="url")[target][:5]
Out[3]:
4516     Frankfurt
14759    Frankfurt
3848     Stuttgart
8757     Frankfurt
35214    Frankfurt
Name: labels, dtype: object
```

A second test I did was to compare the model performance on the predictions:

```
In[4]:
from sklearn.metrics import accuracy_score
accuracy_score(test_generator.classes, np.argmax(preds,axis=-1))

Out[4]:
0.5573770491803278

In[5]:
labels_encoded = [class_list.index(x) for x in test_data.labels.values]
accuracy_score(labels_encoded, np.argmax(preds,axis=-1))
Out[5]:
0.2819672131147541
```

The picture becomes clearer looking at the confusion matrix, which I will omit here in order not to get too lengthy. 


Regarding: 

> Also I don't know why are you paring filenames and preds in the same Dataframe row by row. filenames do not represent the order the filenames are consumed, is just the collection of valid filenames found.

Ok I was not aware of this, for me however it seems to work out since the order of the filenames returned is alphabetically, which seem to be the same case for the predictions of my test_generator (see above). In my test I reconstruct this order by sorting by "url" which are my filenames. Also I thought that this procedure of matching predictions using generator.filenames is the same that @Vijayabhaskar96  suggested or am I not understanding this correctly?

Thank you very much for your help on this!

**Comment by rragundez** [comment] 2019-01-09 21:18
What is `class_list`? And why do you use it to get the classes as strings?  the documentation does not say that will be the order of the classes it only states that those will be classes to be used. To convert back labels integers to classes strings you should use the attribute `class_indices`. Perhaps this is the confusion. Let me know and I'll check tomorrow if still not clear.

**Comment by aarondt** [comment] 2019-01-09 22:20
`class_list `is just` test_data[target].unique().tolist()`, so basically just a list of possible classes. Hence I am using `class_list ` exactly as you describe - just to define possible classes. Observing my tests above I am pretty sure that the generator simply does not yield the correct order i.e. the order of my original dataframe. Something seems to be broken in my process but I cannot figure out what it is :S

**Comment by rragundez** [comment] 2019-01-10 04:36
Can you use the attribute `class_indices` of the class and not `class_list` for the conversion.

**Comment by rragundez** [comment] 2019-01-10 05:53
I just checked and indeed there is your confusion. The generator works as expected, here a self contained example

```
import numpy as np
import scipy.misc
import pandas as pd
import random
from keras_preprocessing.image import ImageDataGenerator


filenames = []
for i in range(30):
    filename = '/tmp/{}.jpg'.format(i)
    scipy.misc.imsave(filename, np.random.normal(size=(30, 30, 3)))
    filenames.append(filename)

df = pd.DataFrame({'filename': filenames, 'class': ['dog', 'cat', 'horse'] * 10}).sample(frac=1).reset_index(drop=True)
classes_list = df['class'].unique().tolist()

test_generator = ImageDataGenerator().flow_from_dataframe(
    df,
    classes=classes_list,
    target_size=(30, 30),
    shuffle = False,
    class_mode='categorical',
)

labels_to_classes = {v:k for k,v in test_generator.class_indices.items()}
assert df['class'].tolist()[:5] == [labels_to_classes[x] for x in test_generator.classes][:5]
```
@Dref360 you can close this issue

**Comment by rragundez** [comment] 2019-01-10 09:01
In addition I added a full minimal example, which contains the check on the previous one plus a model that overfits on the data such that when testing it should predict all the classes correctly if it is in the same order, and indeed it is. I hope this is clear now @aarondt 
```
import numpy as np
import scipy.misc
import pandas as pd
import random
from keras_preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

classes = ['dog', 'cat'] * 1000

filenames = []
for i, cls in enumerate(classes):
    filename = '/tmp/{}.jpg'.format(i)
    pixel_val = 1 if cls == 'cat' else 0
    plt.imsave(filename, pixel_val * np.ones((3, 3, 3)))
    filenames.append(filename)

df = pd.DataFrame({'filename': filenames, 'class': classes}).sample(frac=1).reset_index(drop=True)
classes_list = df['class'].unique().tolist()

train_generator = ImageDataGenerator(rescale=1/255).flow_from_dataframe(
    df,
    classes=classes_list,
    batch_size=1000,
    target_size=(3, 3),
    shuffle = True,
    class_mode='binary',
)

labels_to_classes = {v:k for k,v in train_generator.class_indices.items()}
assert df['class'].tolist()[:5] == [labels_to_classes[x] for x in train_generator.classes][:5]

from keras.models import Sequential
from keras.layers import Flatten, Dense

model = Sequential()
model.add(Flatten(input_shape=(3, 3, 3)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit_generator(train_generator, epochs=2, steps_per_epoch=10)

test_generator = ImageDataGenerator(rescale=1/255).flow_from_dataframe(
    df,
    classes=classes_list,
    batch_size=100,
    target_size=(3, 3),
    shuffle = False,
    class_mode='binary',
)

predict = (np.squeeze(model.predict_generator(test_generator, steps=1)) > 0.5).astype(int)
assert np.all(predict == df['class'].map(test_generator.class_indices)[:len(predict)])
```

**Comment by rragundez** [comment] 2019-01-12 17:55
@aarondt can you close this issue?

**Comment by aarondt** [comment] 2019-01-13 21:56
@rragundez I did try your example on my machine but it keeps failing. Let me explain what I did:

First I realize I get an error which tells me I need to add the `directory` argument to `flow_from_dataframe()`

`TypeError: flow_from_dataframe() missing 1 required positional argument: 'directory'`

As such, I wonder are maybe using a different version? I am using Keras version 2.2.4

Hence, I adjust your code example by adding the directory argument and changing the filenames so they do not include the full path. This allows me to run the code. Now it looks like this:


```
import numpy as np
import scipy.misc
import pandas as pd
import random
from keras_preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import os

classes = ['dog', 'cat'] * 1000


for i, cls in enumerate(classes):
    filename = 'C:/Users/aaron/Desktop/about/tmp/{}.jpg'.format(i)
    pixel_val = 1 if cls == 'cat' else 0
    plt.imsave(filename, pixel_val * np.ones((3, 3, 3)))
    
    
filenames = []
for i in os.listdir("C:/Users/aaron/Desktop/about/tmp/"):
    #print(i)
    filenames.append(i)

df = pd.DataFrame({'filename': filenames, 'class': classes}).sample(frac=1).reset_index(drop=True)
classes_list = df['class'].unique().tolist()

train_generator = ImageDataGenerator(rescale=1/255).flow_from_dataframe(
    df,
    directory = "C:/Users/aaron/Desktop/about/tmp/",
    classes=classes_list,
    batch_size=1000,
    target_size=(3, 3),
    shuffle = True,
    class_mode='binary',
)

labels_to_classes = {v:k for k,v in train_generator.class_indices.items()}
assert df['class'].tolist()[:5] == [labels_to_classes[x] for x in train_generator.classes][:5]
```

running the code up to this point will stop at the assertion giving me the following error:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-2-ef25a72e3929> in <module>
----> 1 assert df['class'].tolist()[:5] == [labels_to_classes[x] for x in train_generator.classes][:5]

AssertionError: 
```


Next, I run the model code:


```
from keras.models import Sequential
from keras.layers import Flatten, Dense

model = Sequential()
model.add(Flatten(input_shape=(3, 3, 3)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit_generator(train_generator, epochs=2, steps_per_epoch=10)

test_generator = ImageDataGenerator(rescale=1/255).flow_from_dataframe(
    df,
    directory = "C:/Users/aaron/Desktop/about/tmp/",
    classes=classes_list,
    batch_size=100,
    target_size=(3, 3),
    shuffle = False,
    class_mode='binary',
)

predict = (np.squeeze(model.predict_generator(test_generator, steps=1)) > 0.5).astype(int)
assert np.all(predict == df['class'].map(test_generator.class_indices)[:len(predict)])

```
And again, it stops at the assertion:

```
Epoch 1/2
10/10 [==============================] - 3s 304ms/step - loss: 0.6932 - acc: 0.5001
Epoch 2/2
10/10 [==============================] - 3s 294ms/step - loss: 0.6932 - acc: 0.5050
Found 2000 images belonging to 2 classes.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-47f613c580a8> in <module>
     20 
     21 predict = (np.squeeze(model.predict_generator(test_generator, steps=1)) > 0.5).astype(int)
---> 22 assert np.all(predict == df['class'].map(test_generator.class_indices)[:len(predict)])

AssertionError: 

```

Now I see the exact same behaviour as in my example above:
`
```
[labels_to_classes[x] for x in test_generator.classes][:5]`
>>['dog', 'cat', 'dog', 'cat', 'dog']
```
And:
```
df['class'].values.tolist()[:5]
>> ['cat', 'cat', 'cat', 'dog', 'dog']
```
No match. But now:
```
df.sort_values(by="filename")['class'].values.tolist()[:5]
>> ['dog', 'cat', 'dog', 'cat', 'dog']

```

Perfect match.

At this point I realize something seems to be broken with my system as I do certainly believe you that this is supposed to be working in general. However, I have no clue whatsoever on what could be broken. Any suggestion on what I might need to check / upgrade / reinstall?

Thank you so much for you help so far!

**Comment by Vijayabhaskar96** [comment] 2019-01-14 03:50
I believe you are using an old version of Keras preprocessing,uninstall it,install the GitHub version of it and retry..

**Closed** 2019-01-14 05:36 UTC
Labels: image

**Comment by aarondt** [comment] 2019-02-09 22:12
@Vijayabhaskar96 I finally managed to solve this. Turns out I had to downgrade keras-preprocessing from 1.0.9 to 1.0.5 and now everything works perfectly i.e. no assertion errors in the above example

**Comment by bkanuka** [comment] 2019-03-28 18:17
To those coming from Google: This bug is still present in the regular `pip install keras` version. In order to upgrade Keras preprocessing, just run `pip install git+https://github.com/keras-team/keras-preprocessing.git`
